# Generated by Django 4.2 on 2024-10-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hierarchcal_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
