# Generated by Django 4.2 on 2024-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_hierarchcal_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
