# Generated by Django 4.2 on 2024-10-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategory'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subservicesmodel',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collection'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='services.servicemodel', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='sub_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='services.subservicesmodel', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_service', to='services.categorymodel', verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='no_of_persons',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.servicemodel', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='subservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservice_category', to='services.subservicesmodel', verbose_name='Collection'),
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.subservicesmodel')),
            ],
        ),
    ]
