# Generated by Django 4.2 on 2024-10-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='subservicesmodel',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='services.servicemodel', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='sub_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='services.subservicesmodel', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_service', to='services.categorymodel', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.servicemodel', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='subservicesmodel',
            name='subservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservice_category', to='services.subservicesmodel', verbose_name='Product'),
        ),
    ]
