# Generated by Django 4.2 on 2024-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
