# Generated by Django 4.2 on 2024-10-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicemodel_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicesmodel',
            name='size',
            field=models.CharField(choices=[('2/3Y', '2/3 Years'), ('3/4Y', '3/4 Years'), ('4/5Y', '4/5 Years'), ('5/6Y', '5/6 Years'), ('6/7Y', '6/7 Years'), ('7/8Y', '7/8 Years'), ('8/9Y', '8/9 Years'), ('9/10Y', '9/10 Years'), ('11/12Y', '11/12 Years'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
